const nodemailer = require("nodemailer");
const log = console.log;

const sendEmail = (email, projectManager, projectNameByIT, mongoID) => {
  //Step 1:
  let transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: process.env.SMTP_PORT,
    secure: process.env.SMTP_SECURE,
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
    tls: {
      rejectUnauthorized: false,
    },
  });

  // Step 2
  let mailOptions = {
    to: email,
    from: '"Evoke Sales Team" <evokepoc@evoketechnologies.com>',
    cc: "thedipakkumaryadav@gmail.com",
    bcc: "deepakumar.dx@gmail.com",
    subject: "Request to share project details.",
    html: ` <p> <b> Dear ${projectManager} </b> </p>
            
            <p> Hope you are doing well. </p>
             You are request to fill the details of <b> ${projectNameByIT} </b> project 
             by clicking <a href = "http://localhost:3000/form/${mongoID}" target="_blank" title="Click to Open the Form"> <b> here. </b> </a>
            <br></br>
            <p> Warm Regards, <br>
                Evoke Sales Teams  </p>
            <br>
            <center><code> <I> <p> This is an autogenerated email, please do not reply :) <br>
            If you have any concerned or query, then please reach out to IT team directly. </p> </I> </code> </center>
          `,
  };

  // Step 3
  transporter.sendMail(mailOptions, (err, info) => {
    if (err) {
      res.json({
        status: "failed to send the mail",
      });
      log("Error occured in sending the mail : " + err);
    } else {
      res.json({
        status: "success",
      });
      log("Mail sent successfully" + info);
    }
  });
};

module.exports = { sendEmail };
