const nodemailer = require("nodemailer");
const log = console.log;

const sendEmail = (email, projectManager, projectNameByIT, mongoID) => {
  //Step 1: Create transporter object that containns SMTP service or host transport detials.
  let transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: process.env.SMTP_PORT,
    secure: process.env.SMTP_SECURE,
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
    tls: {
      rejectUnauthorized: false,
    },
  });

  // Step 2
  let mailOptions = {
    to: email,
    subject: "Request to share project details",
    html: ` <p> <b> Dear ${projectManager} </b> </p>
            <br>
            <p> Hope you are doing well. </p>
            <p> You are request to fill the details of <b> ${projectNameByIT} </b> project by clicking on the below URL. </p>
            <p> http://localhost:3000/form/${mongoID}</p>
            <br>
            <p> Warm Regards, <br>
                IT Teams  </p>
            <br>
            <center><code> <I> <p> This is an autogenerated email, please do not reply :) </p>
            <p> If you have any concerned or query, then please reach out to IT team directly. </p> </I> </code> </center>
          `,
  };

  // Step 3
  transporter.sendMail(mailOptions, (err, info) => {
    if (err) {
      log("Error occured : " + err);
    } else {
      log("Mail sent successfully");
    }
  });
};

module.exports = { sendEmail };
